

[~,~,~,subjs] = exploration_getSubjectsDirsAndRuns();

%ccnl_fmri_con(exploration_expt(), 61, ...
%    {'decRU', 'decTU', 'DV', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);
%ccnl_fmri_con(exploration_expt(), 60, ...
%    {'decRU', 'decTU', 'RU', 'TU', 'RU - TU', 'TU - RU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 59, ...
%    {'DV', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);
%ccnl_fmri_con(exploration_expt(), 58, ...
%    {'RU', 'TU', 'RU - TU', 'TU - RU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 56, ...
%    {'RU', 'trial_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 55, ...
%    {'RU_betas', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 54, ...
%    {'RU', 'TU', 'V', 'VTU', 'RU - TU', 'TU - RU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 53, ...
%    {'RU_betas', 'TU_betas1', 'TU_betas2', 'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 52, ...
%    {'RU_betas', 'TU_betas1', 'TU_betas2', 'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 51, ...
%    {'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 50, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 45, ...
%    {'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);


%ccnl_fmri_con(exploration_expt(), 45, ...
%    {'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 44, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 43, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%{
ccnl_fmri_con(exploration_expt(), 27, ...
    {'both', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 28, ...
    {'diff', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 31, ...
    {'Q1', 'Q2', 'std1', 'std2', 'Q1TU', 'Q2TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 32, ...
    {'Q1', 'Q2', 'std1', 'std2', 'Q1TU', 'Q2TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 33, ...
    {'Q1', 'Q2', 'std1', 'std2', 'Q1TU', 'Q2TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 34, ...
    {'RU', 'TU', 'RRxRU', 'SRxRU', 'RSxRU', 'SSxRU', 'RRxTU', 'SRxTU', 'RSxTU', 'SSxTU', 'RR', 'RS', 'SR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);
 %}

%ccnl_fmri_con(exploration_expt(), 35, ...
%    {'RU', 'TU', 'RU - TU', 'TU - RU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);


ccnl_fmri_con(exploration_expt(), 29, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 24, ...
    {'RU', 'TU', 'RU - TU', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 25, ...
    {'RU', 'TU', 'RU - TU', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 26, ...
    {'RU', 'TU', 'RU - TU', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 30, ...
    {'V', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);




%{
ccnl_fmri_con(exploration_expt(), 14, ...
    {'std1', 'std2', 'DQ1', 'DQ2', 'TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 15, ...
    {'Q1std1', 'Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 16, ...
    {'Q1std1', 'Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 17, ...
    {'std1', 'std2', 'DQ1', 'DQ2', 'TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(exploration_expt(), 18, ...
    {'Q1std1', 'Q2std2', 'Q1std1 - Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 22, ...
    {'Q1std1', 'Q2std2', 'Q1std1 - Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);




ccnl_fmri_con(exploration_expt(), 1, ...
    {'RS + SR - RR - SS', 'RS + SR', 'RR + SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 2, ...
    {'RS + SR - RR - SS', 'RS + SR', 'RR + SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 3, ...
    {'RS + SR - RR - SS', 'RS + SR', 'RR + SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 4, ...
    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 5, ...
    {'RU', 'TU', 'RU - TU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 6, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(exploration_expt(), 7, ...
    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 8, ...
    {'RU', 'TU', 'RU - TU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 9, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);



ccnl_fmri_con(exploration_expt(), 10, ...
    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);
%}

%ccnl_fmri_con(exploration_expt(), 11, ...
%    {'RU', 'TU', 'RU - TU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

ccnl_fmri_con(exploration_expt(), 12, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(exploration_expt(), 13, ...
    {'RU', 'TU', 'RU - TU', 'TU - trial', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(exploration_expt(), 19, ...
    {'RU', 'TU', 'RU - TU', 'TU - RU', 'RU - trial', 'TU - trial', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(exploration_expt(), 21, ...
    {'RU', 'TU', 'RU - TU', 'TU - RU', 'RU - trial', 'TU - trial', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);



%ccnl_fmri_con(exploration_expt(), 1001, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 1002, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 1003, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 1007, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 1008, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 1009, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
