

[~,~,~,subjs] = exploration_getSubjectsDirsAndRuns();

ccnl_fmri_con_nosmooth(exploration_expt(), 1001, ...
    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con_nosmooth(exploration_expt(), 1002, ...
    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con_nosmooth(exploration_expt(), 1003, ...
    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

%ccnl_fmri_con(exploration_expt(), 1007, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 1008, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 1009, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
