

[~,~,~,subjs] = exploration_getSubjectsDirsAndRuns();

%ccnl_fmri_con(exploration_expt(), 1, ...
%    {'RS + SR - RR - SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%%ccnl_fmri_con(exploration_expt(), 2, ...
%%    {'V', 'RU', 'VTU', 'RU - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 3, ...
%    {'RS + SR - RR - SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 4, ...
%    {'RS + SR - RR - SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 5, ...
%    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 6, ...
%    {'RU', '1TU', 'RU - 1TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 7, ...
%    {'V', 'RU', 'TU', 'VTU', 'RU - TU', 'TU - VTU', 'V - VTU', 'RU - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 8, ...
%    {'RU', 'TU', 'RU - TU', 'V', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%ccnl_fmri_con(exploration_expt(), 9, ...
%    {'RU', '1TU', 'RU - 1TU', 'V', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%ccnl_fmri_con(exploration_expt(), 10, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

ccnl_fmri_con(exploration_expt(), 11, ...
    {'Q1', 'Q1std1'}, ...
     subjs);
%ccnl_fmri_con(exploration_expt(), 11, ...
%    {'RU', 'TU', 'V', 'VTU', 'Q1', 'std1', 'std2', 'Q1std1', 'Q2std2', 'Q1TU', 'Q2TU', 'DQ1', 'DQ2','trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(exploration_expt(), 12, ...
%    {'V', 'RU', 'TU', 'DV', 'DV - V', 'RU - TU', 'DV - RU', 'DV - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(exploration_expt(), 13, ...
%    {'V', 'RU', 'TU', 'DV', 'DV - V', 'RU - TU', 'DV - RU', 'DV - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
