EXPT = exploration_expt_nosmooth();

[~,~,~,subjs] = exploration_getSubjectsDirsAndRuns();

%ccnl_fmri_con(EXPT, 62, ...
%    {'RPE', 'RU', 'TU', 'V', 'VTU', 'RU - TU', 'TU - RU', 'trial_onset', 'choice_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);

ccnl_fmri_con(EXPT, 63, ...
    {'PRPE', 'NRPE', 'PRPE - NRPE', 'NRPE - PRPE', 'PRPE + NRPE', 'RU', 'TU', 'V', 'VTU', 'RU - TU', 'TU - RU', 'trial_onset', 'choice_onset', 'feedback_onset_pos', 'feedback_onset_neg', 'trial_onset_L'}, ...
     subjs);

%ccnl_fmri_con(EXPT, 61, ...
%    {'decRU', 'decTU', 'DV', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);
%ccnl_fmri_con(EXPT, 60, ...
%    {'decRU', 'decTU', 'RU', 'TU', 'RU - TU', 'TU - RU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 59, ...
%    {'DV', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);
%ccnl_fmri_con(EXPT, 58, ...
%    {'RU', 'TU', 'RU - TU', 'TU - RU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'feedback_onset', 'trial_onset_L'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 56, ...
%    {'RU', 'trial_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 55, ...
%    {'RU_betas', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 54, ...
%    {'RU', 'TU', 'V', 'VTU', 'RU - TU', 'TU - RU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 53, ...
%    {'RU_betas', 'TU_betas1', 'TU_betas2', 'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 52, ...
%    {'RU_betas', 'TU_betas1', 'TU_betas2', 'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 51, ...
%    {'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 50, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 45, ...
%    {'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);


%ccnl_fmri_con(EXPT, 45, ...
%    {'RU', 'TU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 44, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 43, ...
%    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%{
ccnl_fmri_con(EXPT, 27, ...
    {'both', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 28, ...
    {'diff', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 31, ...
    {'Q1', 'Q2', 'std1', 'std2', 'Q1TU', 'Q2TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 32, ...
    {'Q1', 'Q2', 'std1', 'std2', 'Q1TU', 'Q2TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 33, ...
    {'Q1', 'Q2', 'std1', 'std2', 'Q1TU', 'Q2TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 34, ...
    {'RU', 'TU', 'RRxRU', 'SRxRU', 'RSxRU', 'SSxRU', 'RRxTU', 'SRxTU', 'RSxTU', 'SSxTU', 'RR', 'RS', 'SR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);
 %}

%ccnl_fmri_con(EXPT, 35, ...
%    {'RU', 'TU', 'RU - TU', 'TU - RU', 'V', 'VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);


%{
ccnl_fmri_con(EXPT, 29, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 24, ...
    {'RU', 'TU', 'RU - TU', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 25, ...
    {'RU', 'TU', 'RU - TU', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 26, ...
    {'RU', 'TU', 'RU - TU', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 30, ...
    {'V', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);
%}



%{
ccnl_fmri_con(EXPT, 14, ...
    {'std1', 'std2', 'DQ1', 'DQ2', 'TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 15, ...
    {'Q1std1', 'Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 16, ...
    {'Q1std1', 'Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 17, ...
    {'std1', 'std2', 'DQ1', 'DQ2', 'TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(EXPT, 18, ...
    {'Q1std1', 'Q2std2', 'Q1std1 - Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 22, ...
    {'Q1std1', 'Q2std2', 'Q1std1 - Q2std2', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);




ccnl_fmri_con(EXPT, 1, ...
    {'RS + SR - RR - SS', 'RS + SR', 'RR + SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 2, ...
    {'RS + SR - RR - SS', 'RS + SR', 'RR + SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 3, ...
    {'RS + SR - RR - SS', 'RS + SR', 'RR + SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 4, ...
    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 5, ...
    {'RU', 'TU', 'RU - TU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 6, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(EXPT, 7, ...
    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 8, ...
    {'RU', 'TU', 'RU - TU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 9, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);



ccnl_fmri_con(EXPT, 10, ...
    {'RU', 'TU', 'RU - TU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);
%}

%ccnl_fmri_con(EXPT, 11, ...
%    {'RU', 'TU', 'RU - TU', 'V', 'VTU', 'V - VTU', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%{
ccnl_fmri_con(EXPT, 12, ...
    {'DV', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(EXPT, 13, ...
    {'RU', 'TU', 'RU - TU', 'TU - trial', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);


ccnl_fmri_con(EXPT, 19, ...
    {'RU', 'TU', 'RU - TU', 'TU - RU', 'RU - trial', 'TU - trial', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);

ccnl_fmri_con(EXPT, 21, ...
    {'RU', 'TU', 'RU - TU', 'TU - RU', 'RU - trial', 'TU - trial', 'trial', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
     subjs);
%}


%ccnl_fmri_con(EXPT, 1001, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 1002, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 1003, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);

%ccnl_fmri_con(EXPT, 1007, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 1008, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
%
%ccnl_fmri_con(EXPT, 1009, ...
%    {'G', 'N', 'G + N', 'G - N', 'N - G', 'trial_onset', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
